In [157]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

import descartes
import geopandas as gpd
from shapely.geometry import Point, Polygon
import folium

from scipy import stats


In [158]:
df=pd.read_csv('merged.csv')

In [159]:
pd.set_option('display.max_columns', None)


In [160]:
df=pd.DataFrame(df)
df.head(20)
drop= df['inspector'].value_counts() < 20

In [161]:
df= df.drop(df[['transactions', 'price', 'establishment_x', 'establishment_y', 'address_x', 'address_y', 'trimmed_name_x', 'trimmed_name_y', 'clean_address_x', 'clean_address_y', 'address_distance', 'name_distance']], axis=1)

In [162]:
#Dropped all establishments with less than 22 reviews
df=  df[df['review_count'] >= 22] 
df.describe()

Unnamed: 0  number_of_violations      zip_code  house_numbers  \
count  1820.000000           1820.000000   1820.000000     1820.00000   
mean   1166.184066              5.082967  78220.814286     4784.15989   
std     709.624182              4.892942     15.141757     4756.65303   
min       0.000000              0.000000  78201.000000       21.00000   
25%     529.500000              2.000000  78209.000000      821.00000   
50%    1171.500000              4.000000  78216.000000     2918.00000   
75%    1782.250000              7.000000  78230.000000     8226.50000   
max    2408.000000             50.000000  78259.000000    22211.00000   

           distance  review_count    longitude     latitude       sector  \
count   1820.000000   1820.000000  1820.000000  1820.000000  1820.000000   
mean    7830.619272    210.672527   -98.514171    29.489581    15.985714   
std     3071.065979    288.162365     0.058245     0.055954     9.218967   
min      811.199667     22.000000   -98.708442    29.354318     1.000000   
25%     5929.771588     55.000000   -98.564447    29.433901     8.000000   
50%     7986.163583    109.000000   -98.495517    29.492450    16.000000   
75%     9377.441334    251.000000   -98.480431    29.530199    22.000000   
max    20222.717722   2661.000000   -98.398119    29.661520    35.000000   

       total_score       rating  
count  1820.000000  1820.000000  
mean     93.996154     3.678571  
std       5.436068     0.669349  
min      56.000000     1.000000  
25%      91.000000     3.500000  
50%      95.000000     4.000000  
75%      98.000000     4.000000  
max     100.000000     5.000000

In [163]:
#Dropped all establishments with less than 22 reviews
df=  df[df['review_count'] >= 22] 

In [164]:
df.describe()

Unnamed: 0  number_of_violations      zip_code  house_numbers  \
count  1820.000000           1820.000000   1820.000000     1820.00000   
mean   1166.184066              5.082967  78220.814286     4784.15989   
std     709.624182              4.892942     15.141757     4756.65303   
min       0.000000              0.000000  78201.000000       21.00000   
25%     529.500000              2.000000  78209.000000      821.00000   
50%    1171.500000              4.000000  78216.000000     2918.00000   
75%    1782.250000              7.000000  78230.000000     8226.50000   
max    2408.000000             50.000000  78259.000000    22211.00000   

           distance  review_count    longitude     latitude       sector  \
count   1820.000000   1820.000000  1820.000000  1820.000000  1820.000000   
mean    7830.619272    210.672527   -98.514171    29.489581    15.985714   
std     3071.065979    288.162365     0.058245     0.055954     9.218967   
min      811.199667     22.000000   -98.708442    29.354318     1.000000   
25%     5929.771588     55.000000   -98.564447    29.433901     8.000000   
50%     7986.163583    109.000000   -98.495517    29.492450    16.000000   
75%     9377.441334    251.000000   -98.480431    29.530199    22.000000   
max    20222.717722   2661.000000   -98.398119    29.661520    35.000000   

       total_score       rating  
count  1820.000000  1820.000000  
mean     93.996154     3.678571  
std       5.436068     0.669349  
min      56.000000     1.000000  
25%      91.000000     3.500000  
50%      95.000000     4.000000  
75%      98.000000     4.000000  
max     100.000000     5.000000

In [259]:
#grouped health scores into 5 groups with a range of three
health_scores= {'health_scores' : []}
for x in df['total_score']:
#     print(x)
    if x > 99:
        health_scores['health_scores'].append('1')
    elif x>=96:
        health_scores['health_scores'].append('2')
    elif x >=92:
        health_scores['health_scores'].append('3')
    else :
        health_scores['health_scores'].append('4')
#df
df['health_scores']= health_scores['health_scores']  

In [260]:
#encode for the inspectors
df['inspector'].value_counts()

Lauren Schumacher     180
Jeffrey Carrizales    136
RYAN DAVIS            129
Jacob Johanson        128
Sumner Bumgardner     117
Bamba Njie             89
Diana Garcia           88
Deborah Liu            82
Bernard Capdeboscq     79
Cicily Martinez        77
Valerie Suarez         75
Benito Zuniga          72
Daisy Zamora           68
Nathan Balfour         64
Raul Jimenez           38
John Payelle           38
William Hudson         37
Kassandra Aguilar      35
Debra Hernandez        31
Mario Cavazos          27
Erica Arreola          27
Kathleen Prenzler      26
William Emminger       26
MICHELLE MORENO        26
Amanda Cantu           22
Kacie Patrick          20
Adan Zamora            18
Sean Gilbert           16
Fermin Garza           15
Monica Caballero        7
Victoria Paredes        7
Juanicia Page           6
Joe Mokry               5
Daniel Guzman           3
Maurico Ripley          3
Erica Llanas            2
Rebecca Vera            1
Name: inspector, dtype: int64

In [261]:
#Dropping inspectors that have not copmpleted AT LEAST 20 inspections
vdf = pd.DataFrame(df['inspector'].value_counts())
vdf['check'] = vdf['inspector'] > 1
over_20 = list(vdf.loc[vdf['check'], :].reset_index()['index'])

In [262]:
inspectors = pd.DataFrame(df.inspector.unique())

In [263]:
df['check'] = df['inspector'].isin(over_20)
new_df = df.loc[df['check'], :]
new_df = new_df.drop(columns = ['check', 'Unnamed: 0'])
new_df.head()

inspection_date        inspector  number_of_violations          violations  \
0      2019-01-02  Cicily Martinez                     3  ['22', '29', '45']   
1      2019-03-06       RYAN DAVIS                     1              ['31']   
3      2019-11-04  Cicily Martinez                     3  ['10', '15', '40']   
4      2019-03-14       RYAN DAVIS                     0                  []   
5      2019-03-14       RYAN DAVIS                     1              ['21']   

   zip_code  house_numbers                                        categories  \
0     78212           2524                ['Italian', 'Desserts', 'Seafood']   
1     78230          14439  ['French', 'Asian Fusion', 'Tapas/Small Plates']   
3     78201            914                                       ['Mexican']   
4     78230          13151                                      ['Barbeque']   
5     78230          10003                        ['American (Traditional)']   

      distance  review_count  longitude   latitude                      name  \
0  4950.353662          99.0 -98.493780  29.453730      Capparelli's On Main   
1  9312.955170         102.0 -98.544540  29.573330        Frederick's Bistro   
3  3194.340357          42.0 -98.508619  29.466156            Fina's Kitchen   
4  7935.733616          41.0 -98.537950  29.562850       Bill Miller Bar-B-Q   
5  6996.407916         434.0 -98.536348  29.554391  Green Vegetarian Cuisine   

   sector district  total_score  rating health_scores  
0      35        D           97     3.5             2  
1       9        A           98     4.0             2  
3      35        D           93     4.0             3  
4       9        A          100     2.5             1  
5       9        A           98     4.5             2

In [264]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [265]:
#Will now encode the inspector column to use that as an input for the model

In [266]:
#Label Encoding the inspector column
label_enc= LabelEncoder()
new_df['inspector_encode'] = label_enc.fit_transform(new_df.inspector)

In [267]:
#OneHot Encoding
one_enc = OneHotEncoder()
X = one_enc.fit_transform(new_df.inspector_encode.values.reshape(-1,1)).toarray()
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [268]:
#Joining the encoded data to the main Df
dfOneHot = pd.DataFrame(X, columns = ["health_inspector_"+str(int(i)) for i in range(X.shape[1])])

In [269]:
new_df = new_df.reset_index()
new_df = new_df.reset_index()
new_df['index']= new_df['level_0']
new_df = new_df.drop(columns = ['level_0'])
dfOneHot = dfOneHot.reset_index()
enc_df=new_df.join(dfOneHot, on = 'index', lsuffix='_left', rsuffix='_right')

In [270]:
enc_df.head()

index_left inspection_date        inspector  number_of_violations  \
0           0      2019-01-02  Cicily Martinez                     3   
1           1      2019-03-06       RYAN DAVIS                     1   
2           2      2019-11-04  Cicily Martinez                     3   
3           3      2019-03-14       RYAN DAVIS                     0   
4           4      2019-03-14       RYAN DAVIS                     1   

           violations  zip_code  house_numbers  \
0  ['22', '29', '45']     78212           2524   
1              ['31']     78230          14439   
2  ['10', '15', '40']     78201            914   
3                  []     78230          13151   
4              ['21']     78230          10003   

                                         categories     distance  \
0                ['Italian', 'Desserts', 'Seafood']  4950.353662   
1  ['French', 'Asian Fusion', 'Tapas/Small Plates']  9312.955170   
2                                       ['Mexican']  3194.340357   
3                                      ['Barbeque']  7935.733616   
4                        ['American (Traditional)']  6996.407916   

   review_count  longitude   latitude                      name  sector  \
0          99.0 -98.493780  29.453730      Capparelli's On Main      35   
1         102.0 -98.544540  29.573330        Frederick's Bistro       9   
2          42.0 -98.508619  29.466156            Fina's Kitchen      35   
3          41.0 -98.537950  29.562850       Bill Miller Bar-B-Q       9   
4         434.0 -98.536348  29.554391  Green Vegetarian Cuisine       9   

  district  total_score  rating health_scores  inspector_encode  index_right  \
0        D           97     3.5             2                 5            0   
1        A           98     4.0             2                28            1   
2        D           93     4.0             3                 5            2   
3        A          100     2.5             1                28            3   
4        A           98     4.5             2                28            4   

   health_inspector_0  health_inspector_1  health_inspector_2  \
0                 0.0                 0.0                 0.0   
1                 0.0                 0.0                 0.0   
2                 0.0                 0.0                 0.0   
3                 0.0                 0.0                 0.0   
4                 0.0                 0.0                 0.0   

   health_inspector_3  health_inspector_4  health_inspector_5  \
0                 0.0                 0.0                 1.0   
1                 0.0                 0.0                 0.0   
2                 0.0                 0.0                 1.0   
3                 0.0                 0.0                 0.0   
4                 0.0                 0.0                 0.0   

   health_inspector_6  health_inspector_7  health_inspector_8  \
0                 0.0                 0.0                 0.0   
1                 0.0                 0.0                 0.0   
2                 0.0                 0.0                 0.0   
3                 0.0                 0.0                 0.0   
4                 0.0                 0.0                 0.0   

   health_inspector_9  health_inspector_10  health_inspector_11  \
0                 0.0                  0.0                  0.0   
1                 0.0                  0.0                  0.0   
2                 0.0                  0.0                  0.0   
3                 0.0                  0.0                  0.0   
4                 0.0                  0.0                  0.0   

   health_inspector_12  health_inspector_13  health_inspector_14  \
0                  0.0                  0.0                  0.0   
1                  0.0                  0.0                  0.0   
2                  0.0                  0.0                  0.0   
3                  0.0                  0.0                  0.0   
4           

In [271]:
enc_df.head()

index_left inspection_date        inspector  number_of_violations  \
0           0      2019-01-02  Cicily Martinez                     3   
1           1      2019-03-06       RYAN DAVIS                     1   
2           2      2019-11-04  Cicily Martinez                     3   
3           3      2019-03-14       RYAN DAVIS                     0   
4           4      2019-03-14       RYAN DAVIS                     1   

           violations  zip_code  house_numbers  \
0  ['22', '29', '45']     78212           2524   
1              ['31']     78230          14439   
2  ['10', '15', '40']     78201            914   
3                  []     78230          13151   
4              ['21']     78230          10003   

                                         categories     distance  \
0                ['Italian', 'Desserts', 'Seafood']  4950.353662   
1  ['French', 'Asian Fusion', 'Tapas/Small Plates']  9312.955170   
2                                       ['Mexican']  3194.340357   
3                                      ['Barbeque']  7935.733616   
4                        ['American (Traditional)']  6996.407916   

   review_count  longitude   latitude                      name  sector  \
0          99.0 -98.493780  29.453730      Capparelli's On Main      35   
1         102.0 -98.544540  29.573330        Frederick's Bistro       9   
2          42.0 -98.508619  29.466156            Fina's Kitchen      35   
3          41.0 -98.537950  29.562850       Bill Miller Bar-B-Q       9   
4         434.0 -98.536348  29.554391  Green Vegetarian Cuisine       9   

  district  total_score  rating health_scores  inspector_encode  index_right  \
0        D           97     3.5             2                 5            0   
1        A           98     4.0             2                28            1   
2        D           93     4.0             3                 5            2   
3        A          100     2.5             1                28            3   
4        A           98     4.5             2                28            4   

   health_inspector_0  health_inspector_1  health_inspector_2  \
0                 0.0                 0.0                 0.0   
1                 0.0                 0.0                 0.0   
2                 0.0                 0.0                 0.0   
3                 0.0                 0.0                 0.0   
4                 0.0                 0.0                 0.0   

   health_inspector_3  health_inspector_4  health_inspector_5  \
0                 0.0                 0.0                 1.0   
1                 0.0                 0.0                 0.0   
2                 0.0                 0.0                 1.0   
3                 0.0                 0.0                 0.0   
4                 0.0                 0.0                 0.0   

   health_inspector_6  health_inspector_7  health_inspector_8  \
0                 0.0                 0.0                 0.0   
1                 0.0                 0.0                 0.0   
2                 0.0                 0.0                 0.0   
3                 0.0                 0.0                 0.0   
4                 0.0                 0.0                 0.0   

   health_inspector_9  health_inspector_10  health_inspector_11  \
0                 0.0                  0.0                  0.0   
1                 0.0                  0.0                  0.0   
2                 0.0                  0.0                  0.0   
3                 0.0                  0.0                  0.0   
4                 0.0                  0.0                  0.0   

   health_inspector_12  health_inspector_13  health_inspector_14  \
0                  0.0                  0.0                  0.0   
1                  0.0                  0.0                  0.0   
2                  0.0                  0.0                  0.0   
3                  0.0                  0.0                  0.0   
4           

In [291]:
#### Decision tree including number of review, total violations, yelp score, and inspector
#training / test split
X= enc_df.drop(columns=[ 'index_left', 'inspector_encode', 'index_right', 'inspection_date','longitude', 'latitude',  'inspector', 'number_of_violations','violations', 'zip_code', 'house_numbers', 'categories', 'distance', 'name', 'sector', 'district', 'health_scores', 'total_score'])
y= enc_df['health_scores']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state = 42, stratify=enc_df.health_scores)
X_train.head()


review_count  rating  health_inspector_0  health_inspector_1  \
1650         941.0     4.0                 0.0                 0.0   
318          162.0     3.0                 0.0                 0.0   
1269         382.0     4.0                 0.0                 0.0   
1083         110.0     4.5                 0.0                 0.0   
1187         260.0     3.5                 0.0                 0.0   

      health_inspector_2  health_inspector_3  health_inspector_4  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_5  health_inspector_6  health_inspector_7  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_8  health_inspector_9  health_inspector_10  \
1650                 0.0                 0.0                  0.0   
318                  0.0                 0.0                  0.0   
1269                 0.0                 0.0                  0.0   
1083                 0.0                 0.0                  1.0   
1187                 0.0                 0.0                  0.0   

      health_inspector_11  health_inspector_12  health_inspector_13  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_14  health_inspector_15  health_inspector_16  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_17  health_inspector_18  health_inspector_19  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_20  health_inspector_21  health_inspector_22  \
1650                  0.0                  0.0                  1.0   
318                   0.0                  0.0                  1.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_23  health_inspector_24  health_inspector_25  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_26  health_inspector_27  health_inspector_28  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269

In [324]:
#Train Model

#Create the Decision Tree Object


clf = DecisionTreeClassifier(criterion='entropy', max_depth=4, random_state= 42, min_samples_split= 2)

In [325]:
#Fit the model to the training data

clf.fit(X_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=42, splitter='best')

In [326]:
#enc_df['inspector'].value_counts()

In [327]:
#Estimate health group

y_pred = clf.predict(X_train)
y_pred

array(['4', '4', '2', ..., '2', '4', '2'], dtype=object)

In [328]:
#Estimate the probability of a health group
y_pred_proba = clf.predict_proba(X_train)
y_pred_proba

array([[0.        , 0.        , 0.2962963 , 0.7037037 ],
       [0.        , 0.23728814, 0.23728814, 0.52542373],
       [0.4       , 0.6       , 0.        , 0.        ],
       ...,
       [0.12195122, 0.58536585, 0.14634146, 0.14634146],
       [0.10504202, 0.19747899, 0.32773109, 0.3697479 ],
       [0.17567568, 0.32162162, 0.25      , 0.2527027 ]])

In [329]:
confusion_matrix(y_train, y_pred)

array([[ 54, 153,   0,  25],
       [ 15, 290,   0,  61],
       [  4, 204,   4, 108],
       [  3, 193,   0, 159]])

In [330]:
#Accuracy: number of correct predictions over the number of total instances that have been evaluated.
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))

Accuracy of Decision Tree classifier on training set: 0.40


In [331]:
#Test Model

#Compute the accuracy of the model when run on the test data

print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on test set: 0.40


In [332]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           1       0.71      0.23      0.35       232
           2       0.35      0.79      0.48       366
           3       1.00      0.01      0.02       320
           4       0.45      0.45      0.45       355

    accuracy                           0.40      1273
   macro avg       0.63      0.37      0.33      1273
weighted avg       0.61      0.40      0.33      1273



#### Testing the accuracy with chi square 

In [222]:
#Health scores and inspector
contingency_table = pd.crosstab(enc_df.inspector, enc_df.health_scores)


In [205]:
chi2_stat, p_val, dof, ex = stats.chi2_contingency(contingency_table)
print("===Chi2 Stat===")
print(chi2_stat)
print("\n")
print("===Degrees of Freedom===")
print(dof)
print("\n")
print("===P-Value===")
print(p_val)
print("\n")
print("===Contingency Table===")
print(ex)

===Chi2 Stat===
594.6954946031825


===Degrees of Freedom===
140


===P-Value===
2.5093902147242686e-57


===Contingency Table===
[[ 5.26443101  5.6206707   4.75975811  1.72182518  0.63331501]
 [ 6.43430456  6.86970863  5.81748213  2.104453    0.77405168]
 [26.02968664 27.79109401 23.53435954  8.51346894  3.13139087]
 [21.05772402 22.48268279 19.03903244  6.88730071  2.53326003]
 [23.10500275 24.66849918 20.89004948  7.5568994   2.7795492 ]
 [22.52006597 24.04398021 20.36118747  7.36558549  2.70918087]
 [19.88785047 21.23364486 17.98130841  6.5046729   2.39252336]
 [ 0.87740517  0.93677845  0.79329302  0.28697086  0.1055525 ]
 [23.98240792 25.60527763 21.6833425   7.84387026  2.8851017 ]
 [ 9.06652007  9.68004398  8.19736119  2.96536559  1.09070918]
 [25.73721825 27.47883452 23.26992853  8.41781198  3.09620671]
 [ 7.89664651  8.43100605  7.13963716  2.58273777  0.94997251]
 [ 0.58493678  0.62451897  0.52886201  0.19131391  0.07036833]
 [ 4.38702584  4.68389225  3.96646509  1.43485432  

### Random Forrest

In [333]:
#### Decision tree including number of review, total violations, yelp score, and inspector
#training / test split
X= enc_df.drop(columns=[ 'index_left', 'inspector_encode', 'index_right', 'number_of_violations', 'inspection_date','longitude', 'latitude',  'inspector', 'violations', 'zip_code', 'house_numbers', 'categories', 'distance', 'name', 'sector', 'district', 'health_scores', 'total_score'])
y= enc_df['health_scores']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state = 42, stratify=enc_df.health_scores)
X_train.head()



review_count  rating  health_inspector_0  health_inspector_1  \
1650         941.0     4.0                 0.0                 0.0   
318          162.0     3.0                 0.0                 0.0   
1269         382.0     4.0                 0.0                 0.0   
1083         110.0     4.5                 0.0                 0.0   
1187         260.0     3.5                 0.0                 0.0   

      health_inspector_2  health_inspector_3  health_inspector_4  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_5  health_inspector_6  health_inspector_7  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_8  health_inspector_9  health_inspector_10  \
1650                 0.0                 0.0                  0.0   
318                  0.0                 0.0                  0.0   
1269                 0.0                 0.0                  0.0   
1083                 0.0                 0.0                  1.0   
1187                 0.0                 0.0                  0.0   

      health_inspector_11  health_inspector_12  health_inspector_13  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_14  health_inspector_15  health_inspector_16  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_17  health_inspector_18  health_inspector_19  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_20  health_inspector_21  health_inspector_22  \
1650                  0.0                  0.0                  1.0   
318                   0.0                  0.0                  1.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_23  health_inspector_24  health_inspector_25  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_26  health_inspector_27  health_inspector_28  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269

In [334]:
rf = RandomForestClassifier(bootstrap=True, 
                            class_weight=None, 
                            criterion='gini',
                            min_samples_leaf=3,
                            n_estimators=100,
                            max_depth=3, 
                            random_state=123)

In [335]:
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=3, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=123,
                       verbose=0, warm_start=False)

In [336]:
#Print Feature Importances

print(rf.feature_importances_)

[2.38153948e-01 1.25302523e-01 5.62951710e-04 5.30690170e-03
 2.23777197e-02 1.51808725e-03 0.00000000e+00 2.94906434e-03
 2.65589942e-02 0.00000000e+00 7.90212295e-03 5.07763680e-03
 2.28384169e-02 3.30891916e-03 0.00000000e+00 1.41392112e-03
 9.38158903e-03 1.33835489e-02 7.74047668e-04 6.93422485e-03
 4.16870872e-03 8.94780533e-03 1.60476075e-02 1.17808202e-02
 1.68635844e-01 4.62831818e-04 2.37093422e-03 0.00000000e+00
 0.00000000e+00 2.15381685e-02 1.93227201e-01 1.66721690e-02
 8.72332288e-05 5.05743952e-02 1.26266182e-03 2.47972788e-03
 2.17212404e-03 5.82714979e-03]


In [337]:

y_pred = rf.predict(X_train)
y_pred_proba = rf.predict_proba(X_train)

In [338]:
print('Accuracy of random forest classifier on training set: {:.2f}'
     .format(rf.score(X_train, y_train)))

Accuracy of random forest classifier on training set: 0.45


In [339]:
print(confusion_matrix(y_train, y_pred))

[[ 49 159   1  23]
 [ 16 299  11  40]
 [  6 193  32  89]
 [  3 153  12 187]]


In [245]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           1       0.60      0.45      0.52       372
           2       0.37      0.74      0.49       397
           3       0.59      0.36      0.45       337
           4       0.00      0.00      0.00       122
           5       0.00      0.00      0.00        45

    accuracy                           0.46      1273
   macro avg       0.31      0.31      0.29      1273
weighted avg       0.45      0.46      0.42      1273



/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [340]:
print('Accuracy of random forest classifier on test set: {:.2f}'
     .format(rf.score(X_test, y_test)))

Accuracy of random forest classifier on test set: 0.39


In [247]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

In [248]:
#Create a Gaussian Classifier
model = GaussianNB()

In [249]:
# Train the model using the training sets
model.fit(features,label)

NameError: name 'features' is not defined

In [257]:
#morf = pd.DataFrame(enc_df.groupby('inspector')['total_score'].mean())
mf = """MMMFFMMMFFMMFMMMMFFMFMMFFMFFFFFMFMFMM"""


#sus = pd.DataFrame(sus)

#s = sus['perfect_scores'].mean() - (sus['perfect_scores'].std() * 1)
#print(sus['perfect_scores'].mean() - (sus['perfect_scores'].std() * 2))
#print(sus['perfect_scores'].std())
#sus[(sus['perfect_scores'] > s)]
#mf = """MMMFFMMMFFMMFMMMMFFMFMMFFMFFFFFMFMFMM"""
#sus['ForM'] = list(mf)
#sus.drop(columns = ['MorF'], inplace = True)
#print(len(mf))
#print(len(sus))
#print(sus)
sus['mean_v'] = pd.DataFrame(health.groupby('Inspector')['TOTAL SCORE'].mean()).reset_index()['TOTAL SCORE']
#sus.drop(columns = ['m_score'], inplace = True)
#sus.groupby('ForM')





total_score
inspector                      
Adan Zamora           96.555556
Amanda Cantu          95.727273
Bamba Njie            92.314607
Benito Zuniga         93.055556
Bernard Capdeboscq    93.025316
Cicily Martinez       93.337662
Daisy Zamora          96.205882
Daniel Guzman         94.666667
Deborah Liu           95.219512
Debra Hernandez       96.870968
Diana Garcia          91.693182
Erica Arreola         94.555556
Erica Llanas          97.000000
Fermin Garza          96.200000
Jacob Johanson        93.632812
Jeffrey Carrizales    94.191176
Joe Mokry             94.200000
John Payelle          95.105263
Juanicia Page         84.000000
Kacie Patrick         95.100000
Kassandra Aguilar     90.000000
Kathleen Prenzler     89.192308
Lauren Schumacher     91.205556
MICHELLE MORENO       92.076923
Mario Cavazos         92.370370
Maurico Ripley        98.666667
Monica Caballero      96.714286
Nathan Balfour        96.593750
RYAN DAVIS            98.325581
Raul Jimenez          91.105263
Sean Gilbert          92.312500
Sumner Bumgardner     96.487179
Valerie Suarez        93.480000
Victoria Paredes      92.142857
William Emminger      94.192308
William Hudson        96.108108