In [1]:
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import descartes
import geopandas as gpd
from shapely.geometry import Point, Polygon
import folium
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [42]:
df=pd.read_csv('merged.csv')

In [43]:
pd.set_option('display.max_columns', None)


In [44]:
df=pd.DataFrame(df)
df.head(20)
drop= df['inspector'].value_counts() < 20

In [45]:
df= df.drop(df[['transactions', 'price', 'establishment_x', 'establishment_y', 'address_x', 'address_y', 'trimmed_name_x', 'trimmed_name_y', 'clean_address_x', 'clean_address_y', 'address_distance', 'name_distance']], axis=1)

In [46]:
#Dropped all establishments with less than 22 reviews
df=  df[df['review_count'] >= 22] 
df.describe()

Unnamed: 0  number_of_violations      zip_code  house_numbers  \
count  1820.000000           1820.000000   1820.000000     1820.00000   
mean   1166.184066              5.082967  78220.814286     4784.15989   
std     709.624182              4.892942     15.141757     4756.65303   
min       0.000000              0.000000  78201.000000       21.00000   
25%     529.500000              2.000000  78209.000000      821.00000   
50%    1171.500000              4.000000  78216.000000     2918.00000   
75%    1782.250000              7.000000  78230.000000     8226.50000   
max    2408.000000             50.000000  78259.000000    22211.00000   

           distance  review_count    longitude     latitude       sector  \
count   1820.000000   1820.000000  1820.000000  1820.000000  1820.000000   
mean    7830.619272    210.672527   -98.514171    29.489581    15.985714   
std     3071.065979    288.162365     0.058245     0.055954     9.218967   
min      811.199667     22.000000   -98.708442    29.354318     1.000000   
25%     5929.771588     55.000000   -98.564447    29.433901     8.000000   
50%     7986.163583    109.000000   -98.495517    29.492450    16.000000   
75%     9377.441334    251.000000   -98.480431    29.530199    22.000000   
max    20222.717722   2661.000000   -98.398119    29.661520    35.000000   

       total_score       rating  
count  1820.000000  1820.000000  
mean     93.996154     3.678571  
std       5.436068     0.669349  
min      56.000000     1.000000  
25%      91.000000     3.500000  
50%      95.000000     4.000000  
75%      98.000000     4.000000  
max     100.000000     5.000000

In [47]:
#Dropped all establishments with less than 22 reviews
df=  df[df['review_count'] >= 22] 

In [48]:
#grouped health scores into 5 groups with a range of three
health_scores= {'health_scores' : []}
for x in df['total_score']:
#     print(x)
    if x > 95:
        health_scores['health_scores'].append('1')
    elif x> 90:
        health_scores['health_scores'].append('2')
    else:
        health_scores['health_scores'].append('3')       
#df
df['health_scores']= health_scores['health_scores']  


In [49]:
#df.isnull().sum()
#len(health_scores)
#len(df)
df['inspector'].value_counts()

Lauren Schumacher     180
Jeffrey Carrizales    136
RYAN DAVIS            129
Jacob Johanson        128
Sumner Bumgardner     117
Bamba Njie             89
Diana Garcia           88
Deborah Liu            82
Bernard Capdeboscq     79
Cicily Martinez        77
Valerie Suarez         75
Benito Zuniga          72
Daisy Zamora           68
Nathan Balfour         64
Raul Jimenez           38
John Payelle           38
William Hudson         37
Kassandra Aguilar      35
Debra Hernandez        31
Mario Cavazos          27
Erica Arreola          27
MICHELLE MORENO        26
Kathleen Prenzler      26
William Emminger       26
Amanda Cantu           22
Kacie Patrick          20
Adan Zamora            18
Sean Gilbert           16
Fermin Garza           15
Monica Caballero        7
Victoria Paredes        7
Juanicia Page           6
Joe Mokry               5
Daniel Guzman           3
Maurico Ripley          3
Erica Llanas            2
Rebecca Vera            1
Name: inspector, dtype: int64

In [50]:
vdf = pd.DataFrame(df['inspector'].value_counts())
vdf['check'] = vdf['inspector'] > 1
over_20 = list(vdf.loc[vdf['check'], :].reset_index()['index'])

In [51]:
inspectors = pd.DataFrame(df.inspector.unique())

In [52]:
df['check'] = df['inspector'].isin(over_20)
new_df = df.loc[df['check'], :]
new_df = new_df.drop(columns = ['check'])
new_df

Unnamed: 0      inspection_date           inspector  \
0              0           2019-01-02     Cicily Martinez   
1              1           2019-03-06          RYAN DAVIS   
3              3           2019-11-04     Cicily Martinez   
4              4           2019-03-14          RYAN DAVIS   
5              5           2019-03-14          RYAN DAVIS   
6              6           2019-03-14          RYAN DAVIS   
7              7           2019-07-05     Cicily Martinez   
8              8           2019-07-05     Cicily Martinez   
9              9           2019-07-05          RYAN DAVIS   
10            10           2019-07-05     Cicily Martinez   
11            11           2019-03-19        Daisy Zamora   
12            12           2019-03-19        Daisy Zamora   
13            13           2019-03-19        Daisy Zamora   
14            14           2019-03-19     MICHELLE MORENO   
15            15           2019-11-04     Cicily Martinez   
16            16           2019-11-04     Cicily Martinez   
17            17           2019-11-05   Kassandra Aguilar   
18            18           2019-03-11      Nathan Balfour   
19            19  2019-11-12 00:00:00      Nathan Balfour   
21            21           2019-03-08   Sumner Bumgardner   
22            22           2019-07-15      Jacob Johanson   
23            23           2019-09-17   Sumner Bumgardner   
24            24           2019-07-15      Jacob Johanson   
25            25           2019-03-12     MICHELLE MORENO   
26            26           2019-09-26      Nathan Balfour   
27            27           2019-06-28        Erica Llanas   
28            28           2019-03-20      Nathan Balfour   
29            29           2019-03-20      Nathan Balfour   
30            30           2019-04-02        Diana Garcia   
32            32           2019-10-25     Cicily Martinez   
...          ...                  ...                 ...   
2369        2369           2019-06-04     Debra Hernandez   
2370        2370           2019-06-04        Daisy Zamora   
2372        2372           2019-06-03         Deborah Liu   
2373        2373           2019-05-31      Valerie Suarez   
2374        2374           2019-05-31      Valerie Suarez   
2375        2375           2019-05-31      Jacob Johanson   
2376        2376           2019-05-31      Valerie Suarez   
2377        2377           2019-05-31       Benito Zuniga   
2378        2378           2019-06-03      Valerie Suarez   
2380        2380           2019-06-03       Benito Zuniga   
2381        2381           2019-06-03  Jeffrey Carrizales   
2385        2385           2019-06-13  Jeffrey Carrizales   
2386        2386           2019-06-13  Jeffrey Carrizales   
2388        2388           2019-06-14   Sumner Bumgardner   
2389        2389           2019-06-14  Bernard Capdeboscq   
2390        2390           2019-06-17  Bernard Capdeboscq   
2391        2391           2019-06-17  Bernard Capdeboscq   
2392        2392           2019-06-17        Raul Jimenez   
2393        2393           2019-06-17  Jeffrey Carrizales   
2394        2394           2019-06-17          RYAN DAVIS   
2397        2397           2019-06-11       Juanicia Page   
2399        2399           2019-06-10  Jeffrey Carrizales   
2400        2400           2019-06-10        Diana Garcia   
2401        2401           2019-06-10          RYAN DAVIS   
2403        2403           2019-06-12  Jeffrey Carrizales   
2404        2404           2019-06-11      Nathan Balfour   
2405        2405           2019-06-11      Nathan Balfour   
2406        2406           2019-06-11  Jeffrey Carrizales   
2407        2407           2019-06-11  Jeffrey Carrizales   
2408        2408           2019-06-12  Jeffrey Carrizales   

      number_of_violations                                         violations  \
0                        3                                 ['22', '29', '45']   
1                        1                                   

In [53]:
new_df.describe()

Unnamed: 0  number_of_violations      zip_code  house_numbers  \
count  1819.000000           1819.000000   1819.000000    1819.000000   
mean   1166.623969              5.083562  78220.822980    4786.601979   
std     709.571052              4.894222     15.141376    4756.819669   
min       0.000000              0.000000  78201.000000      21.000000   
25%     530.500000              2.000000  78209.000000     822.500000   
50%    1172.000000              4.000000  78216.000000    2918.000000   
75%    1782.500000              7.000000  78230.000000    8229.000000   
max    2408.000000             50.000000  78259.000000   22211.000000   

           distance  review_count    longitude     latitude       sector  \
count   1819.000000   1819.000000  1819.000000  1819.000000  1819.000000   
mean    7830.658386    210.773502   -98.514180    29.489616    15.979659   
std     3071.910037    288.209398     0.058260     0.055949     9.217881   
min      811.199667     22.000000   -98.708442    29.354318     1.000000   
25%     5929.771588     55.000000   -98.564562    29.434249     8.000000   
50%     7986.163583    109.000000   -98.495517    29.492450    16.000000   
75%     9377.441334    251.000000   -98.480431    29.530199    22.000000   
max    20222.717722   2661.000000   -98.398119    29.661520    35.000000   

       total_score      rating  
count  1819.000000  1819.00000  
mean     93.996701     3.67867  
std       5.437513     0.66952  
min      56.000000     1.00000  
25%      91.000000     3.50000  
50%      95.000000     4.00000  
75%      98.000000     4.00000  
max     100.000000     5.00000

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [15]:
#training / test split
X= new_df[['number_of_violations', 'review_count', 'rating']]
y= new_df['health_scores']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .30, random_state = 123, stratify=new_df.health_scores)

X_train.head()

number_of_violations  review_count  rating
2021                     0         193.0     4.0
186                      2         418.0     3.5
1068                     4         238.0     4.0
513                      4          22.0     3.0
1436                     5         118.0     3.0

In [16]:
# for classification you can change the algorithm to gini or entropy (information gain).  Default is gini.
clf = DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=123)

In [17]:
#Fit the model to the training data

clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=123, splitter='best')

In [18]:
#Estimate health group

y_pred = clf.predict(X_train)
y_pred[1:5]

array(['1', '1', '2', '2'], dtype=object)

In [19]:
#Estimate the probability of a health group
y_pred_proba = clf.predict_proba(X_train)
y_pred_proba

array([[0.91954023, 0.08045977, 0.        ],
       [0.82352941, 0.16806723, 0.00840336],
       [0.47321429, 0.46428571, 0.0625    ],
       ...,
       [0.16129032, 0.55913978, 0.27956989],
       [0.03703704, 0.03703704, 0.92592593],
       [0.82352941, 0.16806723, 0.00840336]])

In [20]:
confusion_matrix(y_train, y_pred)

array([[533,  51,  14],
       [140, 206,  44],
       [ 22,  80, 183]])

In [21]:
#Accuracy: number of correct predictions over the number of total instances that have been evaluated.
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))

Accuracy of Decision Tree classifier on training set: 0.72


In [22]:
#Test Model

#Compute the accuracy of the model when run on the test data

print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on test set: 0.69


In [23]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           1       0.77      0.89      0.82       598
           2       0.61      0.53      0.57       390
           3       0.76      0.64      0.70       285

    accuracy                           0.72      1273
   macro avg       0.71      0.69      0.70      1273
weighted avg       0.72      0.72      0.72      1273



In [24]:
clf

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=123, splitter='best')

In [25]:
#Encoding

In [55]:
#Label Encoding the inspector column
label_enc= LabelEncoder()
new_df['inspector_encode'] = label_enc.fit_transform(new_df.inspector)


In [29]:
#new_df['inspector_encode'].max()

35

In [33]:
#print(len(X[0]))

36


In [56]:
#OneHot Encoding
one_enc = OneHotEncoder()
X = one_enc.fit_transform(new_df.inspector_encode.values.reshape(-1,1)).toarray()
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [89]:
#Joining the encoded data to the main Df
dfOneHot = pd.DataFrame(X, columns = ["health_inspector_"+str(int(i)) for i in range(X.shape[1])])
#print(len(dfOneHot))
#print(len(new_df))
#new_df = pd.concat([new_df, dfOneHot], axis=1)
#new_df=new_df.drop(columns=['inspector_0', 'inspector_1'])
#len(pd.concat([new_df, dfOneHot], axis = 1))
#dfOneHot = dfOneHot.reset_index()
#print(dfOneHot)
#new_df = new_df.reset_index()
#new_df = new_df.drop(columns = ['Unnamed: 0'])
#new_df
#new_one = dfOneHot.reset_index()
#new_one
#new_df

#final = new_one.join(new_df, on = 'index')

1819
1819


In [108]:
#new_df = new_df.reset_index()
#new_df['index']= new_df['level_0']
#new_df['index']
#dfOneHot = dfOneHot.reset_index()
#dfOneHot['index']
new_df.join(dfOneHot, on = 'index', lsuffix='_left', rsuffix='_right')

level_0  index_left      inspection_date           inspector  \
0           0           0           2019-01-02     Cicily Martinez   
1           1           1           2019-03-06          RYAN DAVIS   
2           2           2           2019-11-04     Cicily Martinez   
3           3           3           2019-03-14          RYAN DAVIS   
4           4           4           2019-03-14          RYAN DAVIS   
5           5           5           2019-03-14          RYAN DAVIS   
6           6           6           2019-07-05     Cicily Martinez   
7           7           7           2019-07-05     Cicily Martinez   
8           8           8           2019-07-05          RYAN DAVIS   
9           9           9           2019-07-05     Cicily Martinez   
10         10          10           2019-03-19        Daisy Zamora   
11         11          11           2019-03-19        Daisy Zamora   
12         12          12           2019-03-19        Daisy Zamora   
13         13          13           2019-03-19     MICHELLE MORENO   
14         14          14           2019-11-04     Cicily Martinez   
15         15          15           2019-11-04     Cicily Martinez   
16         16          16           2019-11-05   Kassandra Aguilar   
17         17          17           2019-03-11      Nathan Balfour   
18         18          18  2019-11-12 00:00:00      Nathan Balfour   
19         19          19           2019-03-08   Sumner Bumgardner   
20         20          20           2019-07-15      Jacob Johanson   
21         21          21           2019-09-17   Sumner Bumgardner   
22         22          22           2019-07-15      Jacob Johanson   
23         23          23           2019-03-12     MICHELLE MORENO   
24         24          24           2019-09-26      Nathan Balfour   
25         25          25           2019-06-28        Erica Llanas   
26         26          26           2019-03-20      Nathan Balfour   
27         27          27           2019-03-20      Nathan Balfour   
28         28          28           2019-04-02        Diana Garcia   
29         29          29           2019-10-25     Cicily Martinez   
...       ...         ...                  ...                 ...   
1789     1789        1789           2019-06-04     Debra Hernandez   
1790     1790        1790           2019-06-04        Daisy Zamora   
1791     1791        1791           2019-06-03         Deborah Liu   
1792     1792        1792           2019-05-31      Valerie Suarez   
1793     1793        1793           2019-05-31      Valerie Suarez   
1794     1794        1794           2019-05-31      Jacob Johanson   
1795     1795        1795           2019-05-31      Valerie Suarez   
1796     1796        1796           2019-05-31       Benito Zuniga   
1797     1797        1797           2019-06-03      Valerie Suarez   
1798     1798        1798           2019-06-03       Benito Zuniga   
1799     1799        1799           2019-06-03  Jeffrey Carrizales   
1800     1800        1800           2019-06-13  Jeffrey Carrizales   
1801     1801        1801           2019-06-13  Jeffrey Carrizales   
1802     1802        1802           2019-06-14   Sumner Bumgardner   
1803     1803        1803           2019-06-14  Bernard Capdeboscq   
1804     1804        1804           2019-06-17  Bernard Capdeboscq   
1805     1805        1805           2019-06-17  Bernard Capdeboscq   
1806     1806        1806           2019-06-17        Raul Jimenez   
1807     1807        1807           2019-06-17  Jeffrey Carrizales   
1808     1808        1808           2019-06-17          RYAN DAVIS   
1809     1809        1809           2019-06-11       Juanicia Page   
1810     1810        1810           2019-06-10  Jeffrey Carrizales   
1811     1811        1811           2019-06-10        Diana Garcia   
1812     1812        1812           2019-06-10          RYAN DAVIS   
1813     1813        1813           2019-06-12  Jeffrey Carrizales   
1814     1814   

In [109]:
new_df.dropna()
new_df.isnull().sum()

level_0                 0
index                   0
inspection_date         0
inspector               0
number_of_violations    0
violations              0
zip_code                0
house_numbers           0
categories              0
distance                0
review_count            0
longitude               0
latitude                0
name                    0
sector                  0
district                0
total_score             0
rating                  0
health_scores           0
inspector_encode        0
dtype: int64

In [112]:
#### Decision tree including number of review, total violations, yelp score, and inspector
#training / test split
X1= new_df.drop(columns=['inspection_date', 'inspector', 'violations', 'zip_code', 'house_numbers', 'categories', 'distance', 'longitude', 'latitude', 'name', 'sector', 'district', 'health_scores'])
y1= new_df['health_scores']

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size = .30, random_state = 123, stratify=new_df.health_scores)
X_train1.head()

level_0  index  number_of_violations  review_count  total_score  rating  \
1532     1532   1532                     0         193.0          100     4.0   
163       163    163                     2         418.0           96     3.5   
846       846    846                     4         238.0           93     4.0   
442       442    442                     4          22.0           94     3.0   
1109     1109   1109                     5         118.0           90     3.0   

      inspector_encode  
1532                14  
163                 27  
846                 14  
442                 31  
1109                 8

In [120]:
# for classification you can change the algorithm to gini or entropy (information gain).  Default is gini.
clf1 = DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=123)

In [121]:
clf1.fit(X_train1, y_train1)

NameError: name 'X_train1' is not defined

In [122]:
#Estimate health group

y_pred1 = clf1.predict(X_train1)
y_pred1[1:5]

NameError: name 'X_train1' is not defined

In [123]:
#Estimate the probability of a health group
y_pred_proba1 = clf1.predict_proba1(X_train1)
y_pred_proba1

AttributeError: 'DecisionTreeClassifier' object has no attribute 'predict_proba1'

In [124]:
confusion_matrix(y_train1, y_pred1)

NameError: name 'y_train1' is not defined

In [119]:
#Accuracy: number of correct predictions over the number of total instances that have been evaluated.
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf1.score(X_train1, y_train1)))

Accuracy of Decision Tree classifier on training set: 1.00
