In [105]:
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import descartes
import geopandas as gpd
from shapely.geometry import Point, Polygon
import folium
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from scipy import stats

In [106]:
df=pd.read_csv('merged.csv')

In [107]:
pd.set_option('display.max_columns', None)


In [108]:
df=pd.DataFrame(df)
df.head(20)
drop= df['inspector'].value_counts() < 20

In [109]:
df= df.drop(df[['transactions', 'price', 'establishment_x', 'establishment_y', 'address_x', 'address_y', 'trimmed_name_x', 'trimmed_name_y', 'clean_address_x', 'clean_address_y', 'address_distance', 'name_distance']], axis=1)

In [110]:
#Dropped all establishments with less than 22 reviews
df=  df[df['review_count'] >= 22] 
df.describe()

Unnamed: 0  number_of_violations      zip_code  house_numbers  \
count  1820.000000           1820.000000   1820.000000     1820.00000   
mean   1166.184066              5.082967  78220.814286     4784.15989   
std     709.624182              4.892942     15.141757     4756.65303   
min       0.000000              0.000000  78201.000000       21.00000   
25%     529.500000              2.000000  78209.000000      821.00000   
50%    1171.500000              4.000000  78216.000000     2918.00000   
75%    1782.250000              7.000000  78230.000000     8226.50000   
max    2408.000000             50.000000  78259.000000    22211.00000   

           distance  review_count    longitude     latitude       sector  \
count   1820.000000   1820.000000  1820.000000  1820.000000  1820.000000   
mean    7830.619272    210.672527   -98.514171    29.489581    15.985714   
std     3071.065979    288.162365     0.058245     0.055954     9.218967   
min      811.199667     22.000000   -98.708442    29.354318     1.000000   
25%     5929.771588     55.000000   -98.564447    29.433901     8.000000   
50%     7986.163583    109.000000   -98.495517    29.492450    16.000000   
75%     9377.441334    251.000000   -98.480431    29.530199    22.000000   
max    20222.717722   2661.000000   -98.398119    29.661520    35.000000   

       total_score       rating  
count  1820.000000  1820.000000  
mean     93.996154     3.678571  
std       5.436068     0.669349  
min      56.000000     1.000000  
25%      91.000000     3.500000  
50%      95.000000     4.000000  
75%      98.000000     4.000000  
max     100.000000     5.000000

In [111]:
#Dropped all establishments with less than 22 reviews
df=  df[df['review_count'] >= 22] 

In [112]:
df.describe()

Unnamed: 0  number_of_violations      zip_code  house_numbers  \
count  1820.000000           1820.000000   1820.000000     1820.00000   
mean   1166.184066              5.082967  78220.814286     4784.15989   
std     709.624182              4.892942     15.141757     4756.65303   
min       0.000000              0.000000  78201.000000       21.00000   
25%     529.500000              2.000000  78209.000000      821.00000   
50%    1171.500000              4.000000  78216.000000     2918.00000   
75%    1782.250000              7.000000  78230.000000     8226.50000   
max    2408.000000             50.000000  78259.000000    22211.00000   

           distance  review_count    longitude     latitude       sector  \
count   1820.000000   1820.000000  1820.000000  1820.000000  1820.000000   
mean    7830.619272    210.672527   -98.514171    29.489581    15.985714   
std     3071.065979    288.162365     0.058245     0.055954     9.218967   
min      811.199667     22.000000   -98.708442    29.354318     1.000000   
25%     5929.771588     55.000000   -98.564447    29.433901     8.000000   
50%     7986.163583    109.000000   -98.495517    29.492450    16.000000   
75%     9377.441334    251.000000   -98.480431    29.530199    22.000000   
max    20222.717722   2661.000000   -98.398119    29.661520    35.000000   

       total_score       rating  
count  1820.000000  1820.000000  
mean     93.996154     3.678571  
std       5.436068     0.669349  
min      56.000000     1.000000  
25%      91.000000     3.500000  
50%      95.000000     4.000000  
75%      98.000000     4.000000  
max     100.000000     5.000000

In [9]:
# #grouped health scores into 5 groups with a range of three
# health_scores= {'health_scores' : []}
# for x in df['total_score']:
# #     print(x)
#     if x >= 98:
#         health_scores['health_scores'].append('1')
#     elif x>=94:
#         health_scores['health_scores'].append('2')
#     elif x >=89:
#         health_scores['health_scores'].append('3')
#     elif x >=82:
#         health_scores['health_scores'].append('4')
#     else :
#         health_scores['health_scores'].append('5')
# #df
# df['health_scores']= health_scores['health_scores']  

In [141]:
#grouped health scores into 5 groups with a range of three
health_scores= {'health_scores' : []}
for x in df['total_score']:
#     print(x)
    if x > 99:
        health_scores['health_scores'].append('1')
    elif x>=96:
        health_scores['health_scores'].append('2')
    elif x >=92:
        health_scores['health_scores'].append('3')
    else :
        health_scores['health_scores'].append('4')
#df
df['health_scores']= health_scores['health_scores']  

In [142]:
df['health_scores'].value_counts()

2    523
4    508
3    458
1    331
Name: health_scores, dtype: int64

In [143]:
#encode for the inspectors
df['inspector'].value_counts()

Lauren Schumacher     180
Jeffrey Carrizales    136
RYAN DAVIS            129
Jacob Johanson        128
Sumner Bumgardner     117
Bamba Njie             89
Diana Garcia           88
Deborah Liu            82
Bernard Capdeboscq     79
Cicily Martinez        77
Valerie Suarez         75
Benito Zuniga          72
Daisy Zamora           68
Nathan Balfour         64
John Payelle           38
Raul Jimenez           38
William Hudson         37
Kassandra Aguilar      35
Debra Hernandez        31
Erica Arreola          27
Mario Cavazos          27
William Emminger       26
Kathleen Prenzler      26
MICHELLE MORENO        26
Amanda Cantu           22
Kacie Patrick          20
Adan Zamora            18
Sean Gilbert           16
Fermin Garza           15
Victoria Paredes        7
Monica Caballero        7
Juanicia Page           6
Joe Mokry               5
Maurico Ripley          3
Daniel Guzman           3
Erica Llanas            2
Rebecca Vera            1
Name: inspector, dtype: int64

In [144]:
contingency_table = pd.crosstab(df.inspector, df.health_scores, margins=True).reset_index()
contingency_table = contingency_table[contingency_table.All > 20]
contingency_table['less_92'] = round(contingency_table['4']/contingency_table['All'],2)
contingency_table['92_to_95'] = round(contingency_table['3']/contingency_table['All'],2)
contingency_table['96_to_99'] = round(contingency_table['2']/contingency_table['All'],2)
contingency_table['100'] = round(contingency_table['1']/contingency_table['All'],2)
contingency_table

health_scores           inspector    1    2    3    4   All  less_92  \
1                    Amanda Cantu    3    9    9    1    22     0.05   
2                      Bamba Njie    1   21   35   32    89     0.36   
3                   Benito Zuniga   11   18   21   22    72     0.31   
4              Bernard Capdeboscq    9   21   21   28    79     0.35   
5                 Cicily Martinez   10   18   26   23    77     0.30   
6                    Daisy Zamora   14   36   11    7    68     0.10   
8                     Deborah Liu    8   34   30   10    82     0.12   
9                 Debra Hernandez   13   11    3    4    31     0.13   
10                   Diana Garcia    1   14   30   43    88     0.49   
11                  Erica Arreola    6    7    7    7    27     0.26   
14                 Jacob Johanson   16   48   25   39   128     0.30   
15             Jeffrey Carrizales   46   28   26   36   136     0.26   
17                   John Payelle    7   13   13    5    38     0.13   
20              Kassandra Aguilar    2    5    8   20    35     0.57   
21              Kathleen Prenzler    0    6    5   15    26     0.58   
22              Lauren Schumacher    4   26   47  103   180     0.57   
23                MICHELLE MORENO    4    5    6   11    26     0.42   
24                  Mario Cavazos    3    7    8    9    27     0.33   
27                 Nathan Balfour   23   20   18    3    64     0.05   
28                     RYAN DAVIS   81   32   13    3   129     0.02   
29                   Raul Jimenez    4    2   15   17    38     0.45   
32              Sumner Bumgardner   22   61   27    7   117     0.06   
33                 Valerie Suarez   11   22   14   28    75     0.37   
35               William Emminger    5    5   10    6    26     0.23   
36                 William Hudson   11   12   10    4    37     0.11   
37                            All  331  523  458  508  1820     0.28   

health_scores  92_to_95  96_to_99   100  
1                  0.41      0.41  0.14  
2                  0.39      0.24  0.01  
3                  0.29      0.25  0.15  
4                  0.27      0.27  0.11  
5                  0.34      0.23  0.13  
6                  0.16      0.53  0.21  
8                  0.37      0.41  0.10  
9                  0.10      0.35  0.42  
10                 0.34      0.16  0.01  
11                 0.26      0.26  0.22  
14                 0.20      0.38  0.12  
15                 0.19      0.21  0.34  
17                 0.34      0.34  0.18  
20                 0.23      0.14  0.06  
21                 0.19      0.23  0.00  
22                 0.26      0.14  0.02  
23                 0.23      0.19  0.15  
24                 0.30      0.26  0.11  
27                 0.28      0.31  0.36  
28                 0.10      0.25  0.63  
29                 0.39      0.05  0.11  
32                 0.23      0.52  0.19  
33                 0.19      0.29  0.15  
35                 0.38      0.19  0.19  
36                 0.27      0.32  0.30  
37                 0.25      0.29  0.18

In [145]:
#Dropping inspectors that have not copmpleted AT LEAST 20 inspections
vdf = pd.DataFrame(df['inspector'].value_counts())
vdf['check'] = vdf['inspector'] > 1
over_20 = list(vdf.loc[vdf['check'], :].reset_index()['index'])

In [146]:
inspectors = pd.DataFrame(df.inspector.unique())

In [147]:
df['check'] = df['inspector'].isin(over_20)
new_df = df.loc[df['check'], :]
new_df = new_df.drop(columns = ['check', 'Unnamed: 0'])
# new_df.head()

In [148]:
# new_df.merge(contingency_table)

In [149]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [150]:
#Will now encode the inspector column to use that as an input for the model

In [151]:
#Label Encoding the inspector column
label_enc= LabelEncoder()
new_df['inspector_encode'] = label_enc.fit_transform(new_df.inspector)

In [152]:
#OneHot Encoding
one_enc = OneHotEncoder()
X = one_enc.fit_transform(new_df.inspector_encode.values.reshape(-1,1)).toarray()
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [153]:
#Joining the encoded data to the main Df
dfOneHot = pd.DataFrame(X, columns = ["health_inspector_"+str(int(i)) for i in range(X.shape[1])])

In [154]:
new_df = new_df.reset_index()
new_df = new_df.reset_index()
new_df['index']= new_df['level_0']
new_df = new_df.drop(columns = ['level_0'])
dfOneHot = dfOneHot.reset_index()
enc_df=new_df.join(dfOneHot, on = 'index', lsuffix='_left', rsuffix='_right')

In [155]:
new_df.head()

index inspection_date        inspector  number_of_violations  \
0      0      2019-01-02  Cicily Martinez                     3   
1      1      2019-03-06       RYAN DAVIS                     1   
2      2      2019-11-04  Cicily Martinez                     3   
3      3      2019-03-14       RYAN DAVIS                     0   
4      4      2019-03-14       RYAN DAVIS                     1   

           violations  zip_code  house_numbers  \
0  ['22', '29', '45']     78212           2524   
1              ['31']     78230          14439   
2  ['10', '15', '40']     78201            914   
3                  []     78230          13151   
4              ['21']     78230          10003   

                                         categories     distance  \
0                ['Italian', 'Desserts', 'Seafood']  4950.353662   
1  ['French', 'Asian Fusion', 'Tapas/Small Plates']  9312.955170   
2                                       ['Mexican']  3194.340357   
3                                      ['Barbeque']  7935.733616   
4                        ['American (Traditional)']  6996.407916   

   review_count  longitude   latitude                      name  sector  \
0          99.0 -98.493780  29.453730      Capparelli's On Main      35   
1         102.0 -98.544540  29.573330        Frederick's Bistro       9   
2          42.0 -98.508619  29.466156            Fina's Kitchen      35   
3          41.0 -98.537950  29.562850       Bill Miller Bar-B-Q       9   
4         434.0 -98.536348  29.554391  Green Vegetarian Cuisine       9   

  district  total_score  rating health_scores  inspector_encode  
0        D           97     3.5             2                 5  
1        A           98     4.0             2                28  
2        D           93     4.0             3                 5  
3        A          100     2.5             1                28  
4        A           98     4.5             2                28

In [156]:
enc_df.head()

index_left inspection_date        inspector  number_of_violations  \
0           0      2019-01-02  Cicily Martinez                     3   
1           1      2019-03-06       RYAN DAVIS                     1   
2           2      2019-11-04  Cicily Martinez                     3   
3           3      2019-03-14       RYAN DAVIS                     0   
4           4      2019-03-14       RYAN DAVIS                     1   

           violations  zip_code  house_numbers  \
0  ['22', '29', '45']     78212           2524   
1              ['31']     78230          14439   
2  ['10', '15', '40']     78201            914   
3                  []     78230          13151   
4              ['21']     78230          10003   

                                         categories     distance  \
0                ['Italian', 'Desserts', 'Seafood']  4950.353662   
1  ['French', 'Asian Fusion', 'Tapas/Small Plates']  9312.955170   
2                                       ['Mexican']  3194.340357   
3                                      ['Barbeque']  7935.733616   
4                        ['American (Traditional)']  6996.407916   

   review_count  longitude   latitude                      name  sector  \
0          99.0 -98.493780  29.453730      Capparelli's On Main      35   
1         102.0 -98.544540  29.573330        Frederick's Bistro       9   
2          42.0 -98.508619  29.466156            Fina's Kitchen      35   
3          41.0 -98.537950  29.562850       Bill Miller Bar-B-Q       9   
4         434.0 -98.536348  29.554391  Green Vegetarian Cuisine       9   

  district  total_score  rating health_scores  inspector_encode  index_right  \
0        D           97     3.5             2                 5            0   
1        A           98     4.0             2                28            1   
2        D           93     4.0             3                 5            2   
3        A          100     2.5             1                28            3   
4        A           98     4.5             2                28            4   

   health_inspector_0  health_inspector_1  health_inspector_2  \
0                 0.0                 0.0                 0.0   
1                 0.0                 0.0                 0.0   
2                 0.0                 0.0                 0.0   
3                 0.0                 0.0                 0.0   
4                 0.0                 0.0                 0.0   

   health_inspector_3  health_inspector_4  health_inspector_5  \
0                 0.0                 0.0                 1.0   
1                 0.0                 0.0                 0.0   
2                 0.0                 0.0                 1.0   
3                 0.0                 0.0                 0.0   
4                 0.0                 0.0                 0.0   

   health_inspector_6  health_inspector_7  health_inspector_8  \
0                 0.0                 0.0                 0.0   
1                 0.0                 0.0                 0.0   
2                 0.0                 0.0                 0.0   
3                 0.0                 0.0                 0.0   
4                 0.0                 0.0                 0.0   

   health_inspector_9  health_inspector_10  health_inspector_11  \
0                 0.0                  0.0                  0.0   
1                 0.0                  0.0                  0.0   
2                 0.0                  0.0                  0.0   
3                 0.0                  0.0                  0.0   
4                 0.0                  0.0                  0.0   

   health_inspector_12  health_inspector_13  health_inspector_14  \
0                  0.0                  0.0                  0.0   
1                  0.0                  0.0                  0.0   
2                  0.0                  0.0                  0.0   
3                  0.0                  0.0                  0.0   
4           

In [157]:
#### Decision tree including number of review, total violations, yelp score, and inspector
#training / test split
X= enc_df.drop(columns=[ 'index_left', 'inspector_encode', 'index_right','inspection_date','longitude', 'latitude',  'inspector', 'violations', 'zip_code', 'house_numbers', 'categories', 'distance', 'name', 'sector', 'district', 'health_scores', 'total_score'])
y= enc_df['health_scores']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state = 42, stratify=enc_df.health_scores)
X_train.head()





number_of_violations  review_count  rating  health_inspector_0  \
1650                     8         941.0     4.0                 0.0   
318                      6         162.0     3.0                 0.0   
1269                     1         382.0     4.0                 0.0   
1083                     3         110.0     4.5                 0.0   
1187                    15         260.0     3.5                 0.0   

      health_inspector_1  health_inspector_2  health_inspector_3  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_4  health_inspector_5  health_inspector_6  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_7  health_inspector_8  health_inspector_9  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_10  health_inspector_11  health_inspector_12  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  1.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_13  health_inspector_14  health_inspector_15  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_16  health_inspector_17  health_inspector_18  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_19  health_inspector_20  health_inspector_21  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_22  health_inspector_23  health_inspector_24  \
1650                  1.0                  0.0                  0.0   
318                   1.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_25  health_inspector_26  health_inspector_27  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0  

In [158]:
X_test.head()

number_of_violations  review_count  rating  health_inspector_0  \
360                      6          41.0     3.5                 0.0   
647                      7         222.0     3.0                 0.0   
625                      2         123.0     3.5                 0.0   
174                      0         116.0     4.5                 0.0   
1206                     3          45.0     2.5                 0.0   

      health_inspector_1  health_inspector_2  health_inspector_3  \
360                  0.0                 0.0                 0.0   
647                  0.0                 0.0                 0.0   
625                  0.0                 0.0                 0.0   
174                  0.0                 0.0                 0.0   
1206                 0.0                 0.0                 0.0   

      health_inspector_4  health_inspector_5  health_inspector_6  \
360                  0.0                 0.0                 0.0   
647                  0.0                 0.0                 0.0   
625                  0.0                 1.0                 0.0   
174                  0.0                 0.0                 0.0   
1206                 0.0                 0.0                 0.0   

      health_inspector_7  health_inspector_8  health_inspector_9  \
360                  0.0                 0.0                 0.0   
647                  0.0                 0.0                 0.0   
625                  0.0                 0.0                 0.0   
174                  0.0                 0.0                 0.0   
1206                 0.0                 0.0                 0.0   

      health_inspector_10  health_inspector_11  health_inspector_12  \
360                   0.0                  0.0                  0.0   
647                   0.0                  0.0                  0.0   
625                   0.0                  0.0                  0.0   
174                   0.0                  0.0                  0.0   
1206                  0.0                  0.0                  0.0   

      health_inspector_13  health_inspector_14  health_inspector_15  \
360                   0.0                  0.0                  0.0   
647                   0.0                  0.0                  0.0   
625                   0.0                  0.0                  0.0   
174                   0.0                  0.0                  0.0   
1206                  0.0                  1.0                  0.0   

      health_inspector_16  health_inspector_17  health_inspector_18  \
360                   0.0                  0.0                  0.0   
647                   0.0                  0.0                  0.0   
625                   0.0                  0.0                  0.0   
174                   0.0                  0.0                  0.0   
1206                  0.0                  0.0                  0.0   

      health_inspector_19  health_inspector_20  health_inspector_21  \
360                   0.0                  0.0                  0.0   
647                   0.0                  0.0                  0.0   
625                   0.0                  0.0                  0.0   
174                   0.0                  0.0                  0.0   
1206                  0.0                  0.0                  0.0   

      health_inspector_22  health_inspector_23  health_inspector_24  \
360                   1.0                  0.0                  0.0   
647                   1.0                  0.0                  0.0   
625                   0.0                  0.0                  0.0   
174                   0.0                  0.0                  0.0   
1206                  0.0                  0.0                  0.0   

      health_inspector_25  health_inspector_26  health_inspector_27  \
360                   0.0                  0.0                  0.0   
647                   0.0                  0.0                  0.0  

In [159]:
#Train Model

#Create the Decision Tree Object


clf = DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state= 42, min_samples_split= 2)

In [160]:
#Fit the model to the training data

clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=42, splitter='best')

In [161]:
#enc_df['inspector'].value_counts()

In [162]:
#Estimate health group

y_pred = clf.predict(X_train)
y_pred

array(['4', '4', '2', ..., '3', '1', '3'], dtype=object)

In [163]:
#Estimate the probability of a health group
y_pred_proba = clf.predict_proba(X_train)
y_pred_proba

array([[0.        , 0.015625  , 0.3515625 , 0.6328125 ],
       [0.        , 0.015625  , 0.3515625 , 0.6328125 ],
       [0.21428571, 0.76190476, 0.        , 0.02380952],
       ...,
       [0.03539823, 0.28318584, 0.53539823, 0.1460177 ],
       [0.78947368, 0.        , 0.10526316, 0.10526316],
       [0.03539823, 0.28318584, 0.53539823, 0.1460177 ]])

In [164]:
confusion_matrix(y_train, y_pred)

array([[175,  48,   8,   1],
       [  7, 274,  65,  20],
       [  9,  78, 136,  97],
       [ 11,  10,  34, 300]])

In [165]:
#Accuracy: number of correct predictions over the number of total instances that have been evaluated.
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))

Accuracy of Decision Tree classifier on training set: 0.70


In [166]:
#Test Model

#Compute the accuracy of the model when run on the test data

print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on test set: 0.67


In [167]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           1       0.87      0.75      0.81       232
           2       0.67      0.75      0.71       366
           3       0.56      0.42      0.48       320
           4       0.72      0.85      0.78       355

    accuracy                           0.70      1273
   macro avg       0.70      0.69      0.69      1273
weighted avg       0.69      0.70      0.69      1273



In [168]:
from sklearn import tree

In [169]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import tree
from sklearn.datasets import load_wine
from IPython.display import SVG
from graphviz import Source
from IPython.display import display                               
from ipywidgets import interactive

In [170]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
import graphviz
tree = DecisionTreeClassifier().fit(X, y)
feature_names = X.columns
class_names = sorted(y.unique())
dot = export_graphviz(
    tree,
    out_file=None,
    feature_names=feature_names,
    class_names=class_names,  # target value names
    special_characters=True,
    filled=True,  # fill nodes w/ informative colors
    impurity=False,  # show impurity at each node
    leaves_parallel=True,  # all leaves at the bottom
    proportion=True,  # show percentages instead of numbers at each leaf
    rotate=False,  # left to right instead of top-bottom
    rounded=True,  # rounded boxes and sans-serif font
)
graph = graphviz.Source(dot, filename="dtree", format="png")
graph.view(cleanup=True)

dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.219812 to fit


'dtree.png'

In [171]:
import graphviz

from graphviz import Graph

dot_data = export_graphviz(clf, out_file=None) 
graph = graphviz.Source(dot_data) 

graph.render('Health inspector', view=True)

'Health inspector.pdf'

### Will try Latitude and Longitude as a feature 

In [172]:
df_lat= enc_df.drop(columns=[ 'index_left', 'inspector_encode', 'index_right','inspection_date','inspector', 'violations', 'zip_code', 'house_numbers', 'categories', 'distance', 'name', 'sector', 'district',  'total_score'])

In [173]:
X1 = df_lat.drop(columns = ['number_of_violations', 'health_scores'])
y1 = df_lat[['health_scores']]

#Split Data
#### Decision tree including number of review, total violations, yelp score,inspector, latitude/longitude
#training / test split

X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size = .3, random_state = 42, stratify=df_lat.health_scores)
X_train.head()
# X1.head()

review_count  longitude   latitude  rating  health_inspector_0  \
1650         941.0 -98.489261  29.421605     4.0                 0.0   
318          162.0 -98.490010  29.424610     3.0                 0.0   
1269         382.0 -98.509676  29.544727     4.0                 0.0   
1083         110.0 -98.499886  29.493741     4.5                 0.0   
1187         260.0 -98.507971  29.485780     3.5                 0.0   

      health_inspector_1  health_inspector_2  health_inspector_3  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_4  health_inspector_5  health_inspector_6  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_7  health_inspector_8  health_inspector_9  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_10  health_inspector_11  health_inspector_12  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  1.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_13  health_inspector_14  health_inspector_15  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_16  health_inspector_17  health_inspector_18  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_19  health_inspector_20  health_inspector_21  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_22  health_inspector_23  health_inspector_24  \
1650                  1.0                  0.0                  0.0   
318                   1.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_25  health_inspector_26  health_inspector_27  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0  

In [174]:
scaler = MinMaxScaler(copy=True, feature_range=(0,1)).fit(X_train)

In [175]:
#Max Min Scaled
X_train_scaled = pd.DataFrame(scaler.transform(X_train), columns=X_train.columns.values).set_index([X_train.index.values])
X_train_scaled.head()

review_count  longitude  latitude  rating  health_inspector_0  \
1650      0.348238   0.709526  0.219031   0.750                 0.0   
318       0.053050   0.707101  0.228813   0.500                 0.0   
1269      0.136415   0.643439  0.619817   0.750                 0.0   
1083      0.033346   0.675131  0.453848   0.875                 0.0   
1187      0.090186   0.648957  0.427934   0.625                 0.0   

      health_inspector_1  health_inspector_2  health_inspector_3  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_4  health_inspector_5  health_inspector_6  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_7  health_inspector_8  health_inspector_9  \
1650                 0.0                 0.0                 0.0   
318                  0.0                 0.0                 0.0   
1269                 0.0                 0.0                 0.0   
1083                 0.0                 0.0                 0.0   
1187                 0.0                 0.0                 0.0   

      health_inspector_10  health_inspector_11  health_inspector_12  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  1.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_13  health_inspector_14  health_inspector_15  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_16  health_inspector_17  health_inspector_18  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_19  health_inspector_20  health_inspector_21  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_22  health_inspector_23  health_inspector_24  \
1650                  1.0                  0.0                  0.0   
318                   1.0                  0.0                  0.0   
1269                  0.0                  0.0                  0.0   
1083                  0.0                  0.0                  0.0   
1187                  0.0                  0.0                  0.0   

      health_inspector_25  health_inspector_26  health_inspector_27  \
1650                  0.0                  0.0                  0.0   
318                   0.0                  0.0                  0.0   
1269

In [176]:
#Max Min Scaled
X_test_scaled= pd.DataFrame(scaler.transform(X_test), columns=X_test.columns.values).set_index([X_test.index.values])
X_test_scaled.head()

review_count  longitude  latitude  rating  health_inspector_0  \
360       0.007200   0.717496  0.225545   0.625                 0.0   
647       0.075786   0.713122  0.219080   0.500                 0.0   
625       0.038272   0.666439  0.273305   0.625                 0.0   
174       0.035620   0.635463  0.728778   0.875                 0.0   
1206      0.008715   0.793089  0.369787   0.375                 0.0   

      health_inspector_1  health_inspector_2  health_inspector_3  \
360                  0.0                 0.0                 0.0   
647                  0.0                 0.0                 0.0   
625                  0.0                 0.0                 0.0   
174                  0.0                 0.0                 0.0   
1206                 0.0                 0.0                 0.0   

      health_inspector_4  health_inspector_5  health_inspector_6  \
360                  0.0                 0.0                 0.0   
647                  0.0                 0.0                 0.0   
625                  0.0                 1.0                 0.0   
174                  0.0                 0.0                 0.0   
1206                 0.0                 0.0                 0.0   

      health_inspector_7  health_inspector_8  health_inspector_9  \
360                  0.0                 0.0                 0.0   
647                  0.0                 0.0                 0.0   
625                  0.0                 0.0                 0.0   
174                  0.0                 0.0                 0.0   
1206                 0.0                 0.0                 0.0   

      health_inspector_10  health_inspector_11  health_inspector_12  \
360                   0.0                  0.0                  0.0   
647                   0.0                  0.0                  0.0   
625                   0.0                  0.0                  0.0   
174                   0.0                  0.0                  0.0   
1206                  0.0                  0.0                  0.0   

      health_inspector_13  health_inspector_14  health_inspector_15  \
360                   0.0                  0.0                  0.0   
647                   0.0                  0.0                  0.0   
625                   0.0                  0.0                  0.0   
174                   0.0                  0.0                  0.0   
1206                  0.0                  1.0                  0.0   

      health_inspector_16  health_inspector_17  health_inspector_18  \
360                   0.0                  0.0                  0.0   
647                   0.0                  0.0                  0.0   
625                   0.0                  0.0                  0.0   
174                   0.0                  0.0                  0.0   
1206                  0.0                  0.0                  0.0   

      health_inspector_19  health_inspector_20  health_inspector_21  \
360                   0.0                  0.0                  0.0   
647                   0.0                  0.0                  0.0   
625                   0.0                  0.0                  0.0   
174                   0.0                  0.0                  0.0   
1206                  0.0                  0.0                  0.0   

      health_inspector_22  health_inspector_23  health_inspector_24  \
360                   1.0                  0.0                  0.0   
647                   1.0                  0.0                  0.0   
625                   0.0                  0.0                  0.0   
174                   0.0                  0.0                  0.0   
1206                  0.0                  0.0                  0.0   

      health_inspector_25  health_inspector_26  health_inspector_27  \
360                   0.0                  0.0                  0.0   
647                   0.0                  0.0                  0.0   
625 

In [177]:
y_train.head()

health_scores
1650             4
318              4
1269             2
1083             2
1187             4

In [178]:
#Train Model

#Create the Decision Tree Object


clf1 = DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state= 42, min_samples_split= 2)

In [179]:
y_train.health_scores.value_counts()

2    366
4    355
3    320
1    232
Name: health_scores, dtype: int64

In [180]:
#Fit the model to the training data

clf1.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=42, splitter='best')

In [181]:
y_pred = clf1.predict(X_train)
y_pred

array(['4', '4', '2', ..., '2', '4', '2'], dtype=object)

In [182]:
enc_df.health_scores.value_counts()

2    523
4    508
3    457
1    331
Name: health_scores, dtype: int64

In [184]:
#Health scores and inspector
contingency_table = pd.crosstab(enc_df.inspector, enc_df.health_scores).reset_index()
contingency_table
# ones = ['Daisy Zamora', 'Debra Hernandez', 'Jeffrey Carrizales', 'Nathan Balfour', 'RYAN DAVIS']

health_scores           inspector   1   2   3    4
0                     Adan Zamora   4   9   1    4
1                    Amanda Cantu   3   9   9    1
2                      Bamba Njie   1  21  35   32
3                   Benito Zuniga  11  18  21   22
4              Bernard Capdeboscq   9  21  21   28
5                 Cicily Martinez  10  18  26   23
6                    Daisy Zamora  14  36  11    7
7                   Daniel Guzman   1   1   0    1
8                     Deborah Liu   8  34  30   10
9                 Debra Hernandez  13  11   3    4
10                   Diana Garcia   1  14  30   43
11                  Erica Arreola   6   7   7    7
12                   Erica Llanas   1   0   1    0
13                   Fermin Garza   3   8   3    1
14                 Jacob Johanson  16  48  25   39
15             Jeffrey Carrizales  46  28  26   36
16                      Joe Mokry   0   2   2    1
17                   John Payelle   7  13  13    5
18                  Juanicia Page   0   0   1    5
19                  Kacie Patrick   4  10   2    4
20              Kassandra Aguilar   2   5   8   20
21              Kathleen Prenzler   0   6   5   15
22              Lauren Schumacher   4  26  47  103
23                MICHELLE MORENO   4   5   6   11
24                  Mario Cavazos   3   7   8    9
25                 Maurico Ripley   0   3   0    0
26               Monica Caballero   2   3   2    0
27                 Nathan Balfour  23  20  18    3
28                     RYAN DAVIS  81  32  13    3
29                   Raul Jimenez   4   2  15   17
30                   Sean Gilbert   1   5   4    6
31              Sumner Bumgardner  22  61  27    7
32                 Valerie Suarez  11  22  14   28
33               Victoria Paredes   0   1   3    3
34               William Emminger   5   5  10    6
35                 William Hudson  11  12  10    4

In [185]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           1       0.48      0.60      0.53       232
           2       0.45      0.39      0.42       366
           3       0.56      0.12      0.19       320
           4       0.44      0.74      0.55       355

    accuracy                           0.46      1273
   macro avg       0.48      0.46      0.42      1273
weighted avg       0.48      0.46      0.42      1273



In [186]:
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf1.score(X_test, y_test)))

Accuracy of Decision Tree classifier on test set: 0.41


#### Testing the accuracy with chi square 

In [69]:
test_results = stats.chi2_contingency(contingency_table)
test_results

(594.6954946031825,
 2.5093902147242686e-57,
 140,
 array([[ 5.26443101,  5.6206707 ,  4.75975811,  1.72182518,  0.63331501],
        [ 6.43430456,  6.86970863,  5.81748213,  2.104453  ,  0.77405168],
        [26.02968664, 27.79109401, 23.53435954,  8.51346894,  3.13139087],
        [21.05772402, 22.48268279, 19.03903244,  6.88730071,  2.53326003],
        [23.10500275, 24.66849918, 20.89004948,  7.5568994 ,  2.7795492 ],
        [22.52006597, 24.04398021, 20.36118747,  7.36558549,  2.70918087],
        [19.88785047, 21.23364486, 17.98130841,  6.5046729 ,  2.39252336],
        [ 0.87740517,  0.93677845,  0.79329302,  0.28697086,  0.1055525 ],
        [23.98240792, 25.60527763, 21.6833425 ,  7.84387026,  2.8851017 ],
        [ 9.06652007,  9.68004398,  8.19736119,  2.96536559,  1.09070918],
        [25.73721825, 27.47883452, 23.26992853,  8.41781198,  3.09620671],
        [ 7.89664651,  8.43100605,  7.13963716,  2.58273777,  0.94997251],
        [ 0.58493678,  0.62451897,  0.52886201,  

In [70]:
chi2_stat, p_val, dof, ex = stats.chi2_contingency(contingency_table)
print("===Chi2 Stat===")
print(chi2_stat)
print("\n")
print("===Degrees of Freedom===")
print(dof)
print("\n")
print("===P-Value===")
print(p_val)
print("\n")
print("===Contingency Table===")
print(ex)

===Chi2 Stat===
594.6954946031825


===Degrees of Freedom===
140


===P-Value===
2.5093902147242686e-57


===Contingency Table===
[[ 5.26443101  5.6206707   4.75975811  1.72182518  0.63331501]
 [ 6.43430456  6.86970863  5.81748213  2.104453    0.77405168]
 [26.02968664 27.79109401 23.53435954  8.51346894  3.13139087]
 [21.05772402 22.48268279 19.03903244  6.88730071  2.53326003]
 [23.10500275 24.66849918 20.89004948  7.5568994   2.7795492 ]
 [22.52006597 24.04398021 20.36118747  7.36558549  2.70918087]
 [19.88785047 21.23364486 17.98130841  6.5046729   2.39252336]
 [ 0.87740517  0.93677845  0.79329302  0.28697086  0.1055525 ]
 [23.98240792 25.60527763 21.6833425   7.84387026  2.8851017 ]
 [ 9.06652007  9.68004398  8.19736119  2.96536559  1.09070918]
 [25.73721825 27.47883452 23.26992853  8.41781198  3.09620671]
 [ 7.89664651  8.43100605  7.13963716  2.58273777  0.94997251]
 [ 0.58493678  0.62451897  0.52886201  0.19131391  0.07036833]
 [ 4.38702584  4.68389225  3.96646509  1.43485432  

In [71]:
#grouped health scores into 5 groups with a range of three
health_scores= {'health_scores' : []}
for x in df['total_score']:
#     print(x)
    if x == 100:
        health_scores['health_scores'].append('1')
    elif x== 99:
        health_scores['health_scores'].append('2')
    elif x ==98:
        health_scores['health_scores'].append('3')
    elif x == 97:
        health_scores['health_scores'].append('4')
    elif x == 96:
        health_scores['health_scores'].append('5')
    elif x == 95:
        health_scores['health_scores'].append('6')
    elif x == 94:
        health_scores['health_scores'].append('7')
    elif x == 93:
        health_scores['health_scores'].append('8')
    elif x == 92:
        health_scores['health_scores'].append('9')
    else:
        health_scores['health_scores'].append('10')       
#df
df['health_scores']= health_scores['health_scores']  

In [72]:


#grouped health scores into 5 groups with a range of three
health_scores= {'health_scores' : []}
for x in df['total_score']:
#     print(x)
    if x > 98:
        health_scores['health_scores'].append('1')
    elif x> 95:
        health_scores['health_scores'].append('2')
    elif x >92:
        health_scores['health_scores'].append('3')
    elif x > 89:
        health_scores['health_scores'].append('4')  
    else:
        health_scores['health_scores'].append('5')       
#df
df['health_scores']= health_scores['health_scores']  



In [73]:
#grouped health scores into 5 groups with a range of three
health_scores= {'health_scores' : []}
for x in df['total_score']:
#     print(x)
    if x == 100:
        health_scores['health_scores'].append('1')
    elif x== 99:
        health_scores['health_scores'].append('2')
    elif x ==98:
        health_scores['health_scores'].append('3')
    elif x == 97:
        health_scores['health_scores'].append('4')
    elif x == 96:
        health_scores['health_scores'].append('5')
    elif x == 95:
        health_scores['health_scores'].append('6')
    elif x == 94:
        health_scores['health_scores'].append('7')
    elif x == 93:
        health_scores['health_scores'].append('8')
    elif x == 92:
        health_scores['health_scores'].append('9')
    else:
        health_scores['health_scores'].append('10')       
#df
df['health_scores']= health_scores['health_scores'] 